name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: Forest-Fire-Detection
          environment_name: Forest-Fire-Detection-env
          version_label: ${{ github.sha }}
          region: us-east-2
          # The following lines are what eliminates the need for manual zipping
          use_existing_version_if_available: false
          deployment_package: .